# -*- coding: utf-8 -*-
"""tugas 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1Tpp28e0-JsyiDtC5yvrozJeNHSP4xv
"""

print('nomor1')
kendaraan = ['offroad', 'mobil','350', 'hitam', '3' ]
print (kendaraan)
kendaraan.append(10000000)
kendaraan.append('manual')
print(kendaraan)
kendaraan.append('jeep')
print(kendaraan)

print('nomor 2')
print('nomor 1 untuk hitung persegi')
print('nomor 2 untuk hitung lingkaran')
print('nomor 3 untuk menghitung segitiga')
ean = input('mau hitung apa?')

match ean :
    case '1' :
        sisi = int(input('masukan sisi : '))
        persegi = sisi * sisi
        print('hasil luas persegi :', persegi)
    case '2' :
        v = 22/7
        r = int(input('masukan jari2 :'))
        luas = v *r*r
        print('hasil luas lingkaran :', luas)
    case '3' :
        a = int(input('masukan alas :'))
        t = int(input('masukan tinggi :'))
        luassegi = a*t/2
        print('hasil luas segitiga :, luassegi')

        bilangan = int(input("Masukkan bilangan: "))

if bilangan % 2 == 0:
    print("Bilangan", bilangan, "adalah bilangan genap.")
else:
    print("Bilangan", bilangan, "adalah bilangan ganjil.")